name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: ${{ matrix.os_name }} ${{ matrix.arch }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        runs-on: 
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-26-intel
          - macos-26
          - windows-2025
          - windows-11-arm
        include:
          - runs-on: ubuntu-24.04
            os_name: Linux
            arch: amd64
          - runs-on: ubuntu-24.04-arm
            os_name: Linux
            arch: arm64
          - runs-on: macos-26-intel
            os_name: macOS
            arch: amd64
          - runs-on: macos-26
            os_name: macOS
            arch: arm64
          - runs-on: windows-2025
            os_name: Windows
            arch: amd64
          - runs-on: windows-11-arm
            os_name: Windows
            arch: arm64

    defaults:
      run:
        shell: ${{ case(matrix.os_name == 'Windows', 'msys2 {0}', 'bash -e {0}') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: raspberrypi-utils

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: dgibson/dtc
          # tag: v1.8.1
          ref: 8f48565e5cfedc74d3f7512f1e0188e9d85dc1de
          path: dtc

      - name: Checkout
        uses: actions/checkout@v4
        if: runner.os == 'Windows'
        with:
          repository: tronkko/dirent
          # tag: 1.26
          ref: 31db6474b5231c180bd4618c8c90e43af50c86d0
          path: dirent

      - name: Install build dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt install meson

      - name: Install build dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install meson

      - name: Install build dependencies (Windows)
        id: msys2
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          msystem: ${{ case(matrix.arch == 'amd64', 'clang64', 'clangarm64') }}
          update: true
          install: >-
            git
            flex
            bison
          pacboy: >-
            toolchain:p
            cmake:p
            meson:p
            ninja:p
            libyaml:p

      - name: Build dtc
        working-directory: dtc
        run: |
          meson setup -D default_library=static build
          meson compile -C build

      - name: Configure
        working-directory: raspberrypi-utils
        env:
          RUNNER_OS: ${{ runner.os }}
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          base_dir=$(realpath "$(pwd)/..")
          if [[ "$RUNNER_OS" == 'Windows' ]]; then
            base_dir=$(cygpath -m "$base_dir")
          fi
          dtc_dir="$base_dir/dtc"
          injected_lists="$base_dir/InjectCMakeLists.txt"
          printf 'include_directories("%s")\nlink_directories("%s")\n' \
            "$dtc_dir/libfdt" "$dtc_dir/build/libfdt" > "$injected_lists"
          if [[ "$RUNNER_OS" == 'Windows' ]]; then
            printf 'include_directories("%s")\n' "$base_dir/dirent/include" >> "$injected_lists"
          fi
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DENABLE_WERROR=ON \
            -DCMAKE_PROJECT_dtmerge_INCLUDE="$injected_lists"

      - name: Build
        working-directory: raspberrypi-utils
        run: cmake --build build

      - name: Install (stage)
        working-directory: raspberrypi-utils
        run: |
          DESTDIR="$PWD/install" cmake --install build
          echo "$PWD"

      - name: Determine artifact directory
        id: artifact-dir
        working-directory: raspberrypi-utils
        env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
        run: |
          if [[ -n "$MSYS2_LOCATION" ]]; then
            suffix=$(echo "$MSYS2_LOCATION" | sed -E 's#([A-Za-z]):\\##' | sed -E 's#\\#/#g')
            echo "$suffix"
            echo "path=$(cygpath -m "$PWD/install/$suffix")" | tee -a "$GITHUB_OUTPUT"
          else
            echo "path=$PWD/install" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: utils-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.build_type }}
          path: ${{ steps.artifact-dir.outputs.path }}
          if-no-files-found: error
