name: Publish Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    name: Publish the release
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: '*-Release'
          merge-multiple: true
          skip-decompress: true

      - name: Upload binaries to GitHub Release
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        run: |
          gh release upload "$GITHUB_REF_NAME" *.zip --repo "$GITHUB_REPOSITORY"
